const allFacilityCategories = [
  'Air',
  'Bed &amp; Breakfast Accommodation',
  'Boats &amp; Boat Cruises',
  'Houseboats',
  'Camps &amp; Caravan Parks',
  'Conference Operator',
  'Camps',
  'Farmhouses',
  'Guest Houses',
  'Hunting Operator',
  'Hostels',
  'Hotels',
  'Inns',
  'Travel Agencies/Incentive Travel Organiser',
  'Lodges',
  'Motor Coaches',
  'Motels',
  'Motor Vehicles Hire',
  'Non Consumptive Safari Operator',
  'Restaurants',
  'Self Catering Accommodation',
  'Tour Operator',
  'Visitor Activity Facilities',
  'Visitor Attraction Facilities',
  'Curio Shops',
  'External Operators',
  'Motor Cycle',
  'Curio Shops',
  'Conference Organisers',
  'Tour Guides',
  'Visitor Activity Wedding Venue',
];

const regionsEnum = [
  'Harare',
  'Bulawayo',
  'Mutare',
  'Nyanga',
  'Midlands',
  'Masvingo',
  'Kariba',
  'Hwange',
  'Victoria Falls',
  'Beitbridge',
  'Outside Zimbabwe',
  'Binga',
  'Chiredzi',
  'Chivero',
  'Shamva',
  'Birchenough Bridge',
  'Gwanda',
  'Goromonzi',
  'Plumtree',
  'could',
  'Marondera',
  'Dete',
  'Penhalonga',
  'Kwekwe',
  'Norton',
  'Inside Zimbabwe ',
  'Kadoma',
  'Chiredzi',
  'Zvishavane',
  'Karoi',
  'Gweru',
  'Lupane',
  'Rusape ',
  'Bindura',
  'Figtree',
  'Dete',
  'Save',
  'Shamva',
  'Redcliff',
  'Mana Pools ',
  'Shangani',
  'Shurugwi',
  'Mhondoro',
];
const facilityCategories = allFacilityCategories.values;
const regions = regionsEnum.values;

module.exports = facilityCategories;
module.exports = regions;
